apiVersion: apps/v1
kind: Deployment

metedata:
  name: backend-deployment
  namespace: mern-erp-app
  labels:
    app: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pods
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: shivammishra828/erp-backend:v1
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service

metadata:
  name: backend-deployment-service
  namespace: mern-erp-app

spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      nodePort: 31100
