apiVersion: apps/v1
kind: Deployment

metedata:
  name: frontend-deployment
  namespace: mern-erp-app
  labels:
    app: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pods
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: shivammishra828/erp-frontend:v1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service

metadata:
  name: frontend-deployment-service
  namespace: mern-erp-app

spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31000
