apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongodb-deployment
  namespace: mern-erp-app
  labels:
    app: mongo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb-container
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-storage
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-persistent-volume

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mern-erp-app
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP