apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongodb-persistent-volume-claim
  namespace: mern-erp-app

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
