apiVersion: v1
kind: PersistentVolume

metadata:
  name: mongodb-persistent-volume
  namespace: mern-erp-app

spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /data/db
